config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  
  resources :contacts, only: [:new, :create] 
  post "/trade/message" => "trades#email_trade", as: :email_trade
   get "trades/terms_and_conditions", :to => "trades#terms_and_conditions"
   get "trades/privacy_policy", :to => "trades#privacy_policy"
  resources :trades do
    resources :commons
    

  end

  get '/search' => 'trades#search', :as => 'search_trade' 

  
  devise_for :users
   get "users/trades/terms_and_conditions", :to => "trades#terms_and_conditions"
  root to: 'trades#index'
   
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/destroy' => 'devise/registrations#destroy'
  end 
  resources :categories

end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :commons, dependent: :destroy
  has_many_attached :images, dependent: :destroy
  validates_acceptance_of :terms_and_conditions
  validates :terms_and_conditions, acceptance: true
  validates :title, :description, :images, :address, :category,
        :company_name, :telephone, :price, presence: true
  
  validates :images, presence: true, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'], size_range: 1..2.megabytes }
  validates :title, uniqueness: { case_sensitive: false }
   
  resourcify 
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :terms_and_conditions, :privacy_policy]
  
  # GET /trades
  # GET /trades.json
  def index
    @categories = Category.all
  
    cate = params[:cate]

    if cate.present?
      @trades = Trade.where(:category_id => cate).paginate(:page => params[:page], per_page: 8).order('created_at desc')
    else
      @trades = Trade.paginate(:page => params[:page], per_page: 8).order('created_at desc')
    end  

    end


    def search
      @trades = Trade.where("title LIKE ?","%" + params[:q]+ "%").paginate(:page => params[:page], per_page: 8).order('created_at desc')
      @categories = Category.all
    end 

    # GET /trades/1
    # GET /trades/1.json
    def show
    @categories = Category.all
    end

    # GET /trades/new
    def new
      @trade = current_user.trades.build
      @categories = Category.all
    end

    # GET /trades/1/edit
    def edit
      @categories = Category.all
    end

    # POST /trades
    # POST /trades.json
     def create
      @trade = current_user.trades.build(trade_params)
      @categories = Category.all
      respond_to do |format|
        if @trade.save
          format.html { redirect_to @trade, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @trade }
        else
          format.html { render :new }
          format.json { render json: @trade.errors, status: :unprocessable_entity }
          
        end
      end
    end

    # PATCH/PUT /trades/1
    # PATCH/PUT /trades/1.json
    def update
      respond_to do |format|
        if @trade.update(trade_params)
          format.html { redirect_to @trade, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @trade }
        else
          format.html { render :edit }
          format.json { render json: @trade.errors, status: :unprocessable_entity }
        end
       end
    end

  
    # DELETE /trades/1
  
    # DELETE /trades/1.json
  
    # DELETE /trades/1
  # DELETE /trades/1.json
    def destroy
      @trade.destroy
      respond_to do |format|
        format.html { redirect_to trades_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
        @categories = Category.all
      end
    end
     

    private
    # Use callbacks to share common setup or constraints between actions.
      def set_trade
        @trade = Trade.find(params[:id])
        @categories = Category.all

      end

    # Only allow a list of trusted parameters through.
      def trade_params
        params.require(:trade).permit(:title, :description, :category_id, :company_name, :price, :available_date, :link, :address, :telephone, :user_id, :name, images: [])
      end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
 <div class="container-fluid ml-5">
  <div class="card"><div class="row has text-warning">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="card-body">
  <%= simple_form_for(@trade) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <% if @trade.errors.any? %>
      <div id="error_explanation", class="btn btn-sm btn-danger mt-3 mb-3">
       <h2><%= pluralize(trade.errors.count, "Error") %>
prevented this trade from being saved:</h2>
        <ul>
          <% @trade.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= f.label :title %> 
    <div class="field">
    <%= f.text_field :title, maxlength: 100, placeholder: 'Product name', class:'form-control',required: true, autofocus: true, minlength: 100 %><br>
    </div>  
    
    <%= f.label :address %>  <i class="text-white">( You can type number/name of the road , Sector, House number/name )</i>
    <div class="field">
    <%= f.text_field :address, maxlength: 100, placeholder: 'Fill in here ', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div>


     <%= f.label :company_name %>
    <div class="field">
    <%= f.text_field :company_name, maxlength: 100, placeholder: 'Company name', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div> 
     
    
     <%= f.label :telephone %>
    <div class="field">
    <%= f.text_field :telephone, maxlength: 100, placeholder: 'telephone', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div> 


     <%= f.label :Website_link %> <i class="text-white">( EXAMPLE: http: //www.website.com)</i>
    <div class="field">
    <%= f.text_field :link, maxlength: 100, placeholder: 'leave it blank if you dont have one.', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div> 

    
    <%= f.label :description %>
      <div class="field">
      <%= f.text_area :description, placeholder: 'Add everything your clients needs to know!', class:'form-control',required: true, autofocus: true,autofocus: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %><br>
     </div>

    
     <%= f.label :price %> <i></i>
    <div class="field">    <%= f.text_field :price, maxlength: 100, placeholder: 'Price', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div>


       <%= f.label :category %>
    <div class="field">
     <%= f.select :category_id, Category.all.map {|c| [c.category, c.id]}, required: true, autofocus: true, minlength: 100 %><br>
    </div>    
    
      
    <div class="field mt-5">
      <div class="control">
        <%= f.input :images, as: :file, hint: 'Each image uploaded must be less than 2 megabytes', input_html: { multiple: true, direct_upload: true }, label: false, wrapper: false %>
      </div>
    </div>

    <br>
    <div class="text-center">
      <%= f.submit "Save Product", class: "btn btn-success mb-5" %>
      <%= link_to "Back", trades_path, class:" btn btn-primary mb-2 ml-5 mb-5" %>
      <div class="checkbox">
    <label>
      <input type="checkbox" check="check" value="remember-me"> 
      By creating new product you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>
    </label></div>
     </div>
<% end %>
    </div>
</div></div>
  </div>
</div> 

app/views/trades/_sidebar.html.erb
<div class="col-md-4 mt-5 mb-5 column is-3 is-offset-1">
  <p id="notice"><%= notice %></p>

 <% if has_role?(:admin) %>

  <h1 class="title is-5 has-text-grey-light">Categories</h1>
<table>

<strong><p>Category</p></strong>

  <ul class="list">
    <% @categories.each do |category| %>
    <tr>
<td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

    <li><%= link_to category.category, category, class: "has text-dark" %></li>
    <% end %>
  </ul>
</table>
  <br/>

    <%= link_to 'New Category', new_category_path, class:" btn btn-success mb-5" %>
  <% end %>
</div>

app/views/trades/_trade.html.erb
<div class="container-fluid pb-5">
  <div>
    <div class="border col-md-8 pr-0">

  <div class="card-image mb-5 pb-5 pl-3">
    <figure class="image is-square">
      <div style="width:400px; height:80px">
      <%=link_to image_tag(trade.images.first.variant(resize: "250x210!>")), trade %>
      </div>
    </figure>
    
  </div>
  <div class="card-content">
    <h4 class="pt1 title is-5 pt-3 text-center"><%=link_to trade.title, trade, class: "text-warning"%></h4>
    <p class="pv1 has text-white ml-5"><%= truncate(trade.description, length: 30) %></p>
    
    <div class="media pt3">
      <div class="media-left pt3"> </div>
      <div class="media-content">
        <!--<strong><p class="has-text-weight-bold ml-4 mb0 has text-warning lead">Posted by: <%= trade.company_name %></p></strong>-->
        <strong><p class="has-text-weight-bold ml-4 mb0 has text-warning">price: <%= trade.price %></p></strong>
       <strong><p class="is-italic mb0 has text-primary mr-md-auto"><time>posted <%= time_ago_in_words(trade.created_at) %> ago</time></p></strong>
       </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/trades/edit.html.erb
<li class="nav-item dropdown btn-primary mt-4 has text-dark">
        <strong class="nav-link dropdown-toggle has text-white" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search by category</strong>
        <div class="dropdown-menu has text-center" aria-labelledby="dropdown01">
    
       <div class="mr-md-12">
       <div class="card">
       <div class="card-header">
          Categories
        </div>
        <ul class="list-group has text-left bg-dark">

        <% @categories.each do |category| %>

         <li>
          <%= link_to category.category, trades_path(:cate => category.id), class: "has text-white" %>

         <span class="badge badge-primary badge-pill has text-dark bg-warning"><%= category.trades.count %></span>
         </li>  
        <% end %>
        </ul></li>
        </div>
        </div></div></div>

<div class="col-md-8 mt-5 mb-5">

<h1 class="title is-3 text-center">Editing Product</h1>

<%= render 'form', trade: @trade %>
</div>

app/views/trades/index.html.erb
<%= yield (:body_class) %>
    <% if flash[:notice] %>
      <div class="btn btn-sm btn-success notification is-success global-notification list-group mt-4 pt-3">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>    

    <% if flash[:alert] %>
    <div class="btn btn-sm btn-danger notification is-danger global-notification list-group">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
 
        <li class="nav-item dropdown btn-primary mt-3 has text-dark">
        <strong class="nav-link dropdown-toggle has text-white" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search by category</strong>
        <div class="dropdown-menu has text-center" aria-labelledby="dropdown01">
    
       <div class="mr-md-12">
       <div class="card">
       <div class="card-header">
          Categories
        </div>
        <ul class="list-group has text-left bg-primary">

        <% @categories.each do |category| %>
 
         <li>
          <%= link_to category.category, trades_path(:cate => category.id), class: "has text-white" %>

         <span class="badge badge-primary badge-pill has text-dark bg-warning"><%= category.trades.count %></span>
         </li>  
        <% end %>
        </ul></li>
        </div>
        </div></div></div> 


<main role="main">

  <div class="bg-light">
  <div class="mr-md-auto">    
  <div class="container ml-md-10">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
     <%= image_tag('pic1.png', width:700, height:300) %>
    </div>
    <div class="carousel-item">
      <%= image_tag('pic2.png', width:700, height:300) %>
    </div>
    <div class="carousel-item">
     <%= image_tag('pic3.png', width:700, height:300) %>
    </div>
</div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div></div></div>
  </div>
   
 <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron col-sm-12 text-center">
      <h3 class="title is-1">Enjoy our free trials</h3>

    <p class="subtitle is-5">Looking to get more clients for your products!</p>
    </div>
  </div>


  <div class="container-fluid">
  <div class="row">
  <div class="row mb-3 pt-4 pb-4 mr-1">
  <% @trades.each do |trade| %>
   <div class="row">
      <div style="width:25px;">
      </div>
   </div>
  <div class="row ml-3">
    <%= render trade, trade: trade %>
  </div>
  <% end %>
  </div>

 
    </div></div></div></div>
<%= render "trades/sidebar" %>
  </div> <!-- /container -->

</div>
<div class="mb-5 pl-5 ml-5">
<%= will_paginate @trades, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</main>

app/views/trades/new.html.erb
<li class="nav-item dropdown btn-primary mt-4 has text-dark">
        <strong class="nav-link dropdown-toggle has text-white" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search by category</strong>
        <div class="dropdown-menu has text-center" aria-labelledby="dropdown01">
    
       <div class="mr-md-12">
       <div class="card">
       <div class="card-header">
          Categories
        </div>
        <ul class="list-group has text-left bg-dark">

        <% @categories.each do |category| %>

         <li>
          <%= link_to category.category, trades_path(:cate => category.id), class: "has text-white" %>

         <span class="badge badge-primary badge-pill has text-dark bg-warning"><%= category.trades.count %></span>
         </li>  
        <% end %>
        </ul></li>
        </div>
        </div></div></div>

<div class="container-fluid">
<div class="col-md-6 mt-5 mb-5 ml-5 pl-5">

<h1 class="title is-3 text-center">New product</h1>

<%= render 'form', trade: @trade %>

</div>

app/views/trades/search.html.erb
<li class="nav-item dropdown btn-primary mb-5 has text-dark">
        <strong class="nav-link dropdown-toggle has text-white pl-5 mr-5" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search by category</strong>
        <div class="dropdown-menu has text-center" aria-labelledby="dropdown01">
    
       <div class="mr-md-12">
       <div class="card">
       <div class="card-header">
          Categories
        </div>
        <ul class="list-group has text-left bg-dark">

        <% @categories.each do |category| %>

         <li>
          <%= link_to category.category, trades_path(:cate => category.id), class: "has text-white" %>

         <span class="badge badge-primary badge-pill has text-dark bg-warning"><%= category.trades.count %></span>
         </li>  
        <% end %>
        </ul></li>
        </div>
        </div></div></div>


  <div class="pl-5 ml-5">
     <%= will_paginate @trades, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
<div class="container-fluid">
<div class="row mb-5 pb-5">
	 <div class="row">
<div class="col-md-14">



<% if @trades.any? %>

   <h3 class="ml-5 mb-1">Search Results</h3><hr />
   <%= render @trades %>

<% else %>

  <p><h3 class="ml-5 mb-1">Search Results</h3><hr /> <a   class="has-text-center text-white mt-4 btn bg-danger ml-5"  >Sorry!!! Nothing matches your search</a></p>
  <p class="ml-5">Check if all words are spelled correctly</p>
  <p class="ml-5 mb-5">Or search again by category</p>
  <% end %>
</div></div>
</div></div>

app/views/trades/show.html.erb
 <li class="nav-item dropdown btn-primary mt-4 has text-dark">
        <strong class="nav-link dropdown-toggle has text-white" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search by category</strong>
        <div class="dropdown-menu has text-center" aria-labelledby="dropdown01">
    
       <div class="mr-md-12">
       <div class="card">
       <div class="card-header">
          Categories
        </div>
        <ul class="list-group has text-left bg-dark">

        <% @categories.each do |category| %>

         <li>
          <%= link_to category.category, trades_path(:cate => category.id), class: "has text-white" %>

         <span class="badge badge-primary badge-pill has text-dark bg-warning"><%= category.trades.count %></span>
         </li>  
        <% end %>
        </ul></li>
        </div>
        </div></div></div>

  <%= yield (:body_class) %>
    <% if flash[:notice] %>
      <div class="btn btn-sm btn-success notification is-success global-notification mt-3">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="btn btn-sm btn-danger notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    
  <div class="container bg-light">
    <div class="rows">
      <div class="col-md-8 mt-5">
      
      <strong><h1 class="title pb3 border-bottom col-md-7 text-center has text-dark mt-5">Product info</h1></strong>
      <h2 class="lead">Category: <%= @trade.category.category %></h2>       

    <h5 class="title is-1">Product name: <%= @trade.title %></h5>
    <div>
      <strong><p class=" col-md-4 text-primary">Posted <%= time_ago_in_words(@trade.created_at) %> ago</p></strong>

      
      <div class="pt1 pb3 border mb-3 pl-2"><strong class="border-bottom">Product description: </strong><%= sanitize markdown_to_html(@trade.description) %>
      </div>
    

    <div class="row">
      <span class="mb-4 pl-4 col-md-6 has text-warning"> 
        <div class="card-content pt-1 pb-2 lead">
        <div>Posted by: <%= @trade.company_name %><a class="mt-1 mb-1 row text-right"></a>Address: <%= @trade.address %><a class="mt-1 mb-1 row text-right"></a>Contacts: <%= @trade.telephone %><a class="mt-1 row text-right"></a>Price: <%= @trade.price %><a class="mt-1 row text-right"></a></a>Website link: <%= auto_link(@trade.link) %></div></div></div>
      </span>
    </div></div>

        <iframe class="bg-dark border ml-lg-4 mt-3 mb-2" width="480" height="320" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDwPWqzUvZRkWVpkF52SD7uctfnLjDADdw&q=<%= @trade.address.to_param %>" allowfullscreen></iframe>
      
    <% if @trade.images.attached? %>
      
      <div class="row is-multiline pt-4 pl-5 mb-5">
        <% @trade.images.each do |image| %>
          <div class="column is-one-third ">
             <div style="width:380px; height:180px;">
            <%= image_tag image.variant(resize: "320x160>") %>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>


  <div class="content">
  <div class="rows text-center">

    <% if trade_author(@trade) || has_role?(:admin) %>
    <div class="row col-md-3">
      <div class="pa3 mb4 pb-2 border-radius-3 mb-3">
        <p class="f6 pb1 has text-warning">Author actions:</p>

        <div class="button-group">
          <%= link_to "Edit product: #{@trade.title}", edit_trade_path(@trade), class: "btn btn-sm btn btn-secondary mb-2 ml-3 mr-1 " %>
          <%= link_to "Back", trades_path, class: " btn btn-sm btn btn-primary mb-2  mr-3" %>
          <%= button_to 'delete this product?', @trade, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn btn-danger mb-2" %>
        </div>
      </div></div>
    <% end %>


    <!--div class="row">
    <div class="ml-md-auto col-md-8">
      <div class="border mr-5 col-sm-9 mt-3 pt-2 pb-2">
     <button class="btn btn-info text-uppercase mt-3 mb-3">Call <%=@trade.user.name %></button>
     <button class="btn btn-info mt-3 mb-3" data-toggle="modal" data-target="#contact-modal">Email <%=@trade.user.name %></button>
   </div></div></div-->
    

     
   <section class="section comments col-md-5 mt-5 mb-5"><div class="row">
    <div class="container-fluid">
      <h3 class="subtitle is-5 has text-white"><strong><%= @trade.commons.count %></strong> Comments</h3>
        <%= render @trade.commons %>
        <div class="comment-form">
            <h4 class="subtitle is-3 has text-white">Leave a reply</h4>
            <hr />
             <%= render 'commons/form' %>
        </div>
    </div></div>
    </section>

       
    <% if user_signed_in? %>
    
    <% else %>
    <p>To comment you need to <%= link_to 'login', new_user_session_path %>. Don't 
      have an account? <%= link_to 'Sign up', new_user_registration_path %> for one. Thanks!</p>
    <% end %>
</div></div>
</div></div></div>